events {}

http {
    server {
        listen 80;

        # קריאות כלליות ל־Flask
        location / {
            proxy_pass http://workprofile:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # קריאה ל־add
        location /add {
            proxy_pass http://workprofile:5000/add;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # קריאה ל־delete
        location /delete {
            proxy_pass http://workprofile:5000/delete;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
