apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk   # rootpassword ב-base64
  MYSQL_DATABASE: ZXhhbXBsZURi           # exampleDb ב-base64
  MYSQL_USER: Zmxhc2hhcHA=               # flaskapp ב-base64
  MYSQL_PASSWORD: Zmxhc2hhcHBhc3M=       # flaskapp ב-base64

