apiVersion: v1
kind: Service
metadata:
  name: workprofile-service
spec:
  selector:
    app: workprofile
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000

