services:
  mysql:
    image: mysql:8
    container_name: workprofile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s

  workprofile:
    build: ../
    container_name: workprofile-app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    depends_on:
      mysql:
        condition: service_healthy
    restart: always   # מוודא שהקונטיינר ינסה שוב אם נופל

  nginx:
    image: nginx:latest
    container_name: workprofile-nginx
    ports:
      - "8081:8080"  # חיבור חיצוני ל־8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - workprofile
    restart: always

volumes:
  mysql-data:
