name: WorkProfile CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/workprofile-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Run container in detached mode
        run: docker run -d -p 8080:5000 --name workprofile_test $IMAGE_NAME:latest

      - name: Wait for container to start
        run: sleep 10

      - name: Test root endpoint '/'
        run: curl -f http://localhost:8080/

      - name: Test health endpoint '/health'
        run: curl -f http://localhost:8080/health

      - name: Stop and remove test container
        run: |
          docker stop workprofile_test
          docker rm workprofile_test

      - name: Push Docker image to GitHub Container Registry
        if: success()
        run: docker push $IMAGE_NAME:latest

